###############################################################################
## File for Anaconda.org
###############################################################################

{% set name = "leximpact-prepare-data" %}
{% set version = "0.0.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c2a4943cde9810a1bc0af3e023bf2a7934cfcc3cf8d2d18cb44e4d17a5f3fb59

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
    - poetry
  run:
    - python >=3.8,<4.0
    - OpenFisca-France >=113.0.0,<114.0.0
    - diagrams >=0.20.0,<0.21.0
    - leximpact-socio-fisca-simu-etat >=0.1.2,<0.2.0
    - pandas >=1.3.0,<2.0.0
    - python-dotenv >=0.19.2,<0.20.0
    - scikit-learn >=1.0.1,<2.0.0
    - pytables >=3.6.1,<4.0.0
    - typing-extensions >=3.10.0,<4.0.0
    - vaex-core >=4.8.0,<5.0.0
    - seaborn
    - jupyterlab
    - ipykernel >=6.2.0
    - plotly
    - chardet
    - tqdm
    - idna =2.10

test:
  imports:
    - leximpact_prepare_data
  requires:
    - pytest >=4.4.1,<6.0.0
    - pip
  commands:
    #- pip check
    - python -c "from leximpact_prepare_data.calib_and_copules import DistribDeVarVaex; variable_values = [i*10 for i in range(50)]; print(DistribDeVarVaex(variable_values=variable_values,variable='toto',nb_ff=len(variable_values),nb_bucket_var=2,lower_bound=50,upper_bound=1e10,debug=False,).to_dict()['nb_foyer'])"

outputs:
  - name: leximpact-prepare-data

  - name: leximpact-prepare-data-dev
    build:
      noarch: python
    requirements:
      host:
        - python
      run:
        - python >=3.8,<4.0
        - seaborn
        - jupyterlab
        - ipykernel >=6.2.0
        - pytest
        - flake8
        - black
        - nbqa
        - pre-commit
        - papermill
        - nbdev
        - plotly
        - xlrd
        - openpyxl
        - {{ pin_subpackage('leximpact-prepare-data', exact=True) }}

  # Sur le CASD nous n'avons pas besoin des outils de test et de lint ( papermill, black, flake8...)
  # Par contre on ajoute Dask et Vizpy
  - name: leximpact-prepare-data-casd
    build:
      noarch: python
    requirements:
      host:
        - python
      run:
        - python >=3.8,<4.0
        - seaborn
        - jupyterlab
        - ipykernel >=6.2.0
        - plotly
        - xlrd
        - openpyxl
        - dask
        - vispy
        - chardet
        - tqdm
        - idna =2.10
        - {{ pin_subpackage('leximpact-prepare-data', exact=True) }}


about:
  home: https://leximpact.an.fr
  license_family: AGPL
  license: AGPL-3.0-only
  license_file: LICENSE
  summary: "LexImpact Prepare Data"
  doc_url: https://documentation.leximpact.dev/leximpact_prepare_data/
  dev_url: https://git.leximpact.dev/leximpact/leximpact-prepare-data
  description: This package contains the LexImpact pipeline.

extra:
  recipe-maintainers:
    - benoit-cty
